# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74651289383c37ed4f3b30fd20173d223e3f50f3dd914ebfa838c62f7d83666a0ea365ed49be14c5374892b775bc3b2af0648197ef931c96133ef58c847551ce

test:
  secret_key_base: bead546923351eeb08e7f306e0ab02026ee59e8ec91a3c1e88ddcffba10ffdf3b7df3c078713498f645dd1796e396758945f2943647da10ee118e992b9049402

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
